// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_api;

#nullable disable

namespace web_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230120192758_hexTiles_and_Sites")]
    partial class hexTiles_and_Sites
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("web_api.GameModel.AvatarModel.CreatureBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<int>("FellowshipId")
                        .HasColumnType("int");

                    b.Property<int>("Intellect")
                        .HasColumnType("int");

                    b.Property<int>("Lucidity")
                        .HasColumnType("int");

                    b.Property<int>("Morale")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PossessorId")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("Temperament")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FellowshipId");

                    b.HasIndex("PossessorId");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("web_api.GameModel.HexTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<bool>("isBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("HexTiles");
                });

            modelBuilder.Entity("web_api.GameModel.Items.ItemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatureBaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatureBaseId");

                    b.ToTable("ItemBase");
                });

            modelBuilder.Entity("web_api.GameModel.OngoingInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("web_api.GameModel.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Party");
                });

            modelBuilder.Entity("web_api.GameModel.Sites.SiteBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SiteBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SiteBase");
                });

            modelBuilder.Entity("web_api.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RegistrationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TokenCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TokenExpires")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("web_api.UserConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Confirmation");
                });

            modelBuilder.Entity("web_api.GameModel.Sites.SiteInteractive", b =>
                {
                    b.HasBaseType("web_api.GameModel.Sites.SiteBase");

                    b.HasDiscriminator().HasValue("SiteInteractive");
                });

            modelBuilder.Entity("web_api.GameModel.Sites.SiteObstacle", b =>
                {
                    b.HasBaseType("web_api.GameModel.Sites.SiteBase");

                    b.HasDiscriminator().HasValue("SiteObstacle");
                });

            modelBuilder.Entity("web_api.GameModel.AvatarModel.CreatureBase", b =>
                {
                    b.HasOne("web_api.GameModel.Party", "Fellowship")
                        .WithMany()
                        .HasForeignKey("FellowshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api.User", "Possessor")
                        .WithMany()
                        .HasForeignKey("PossessorId");

                    b.Navigation("Fellowship");

                    b.Navigation("Possessor");
                });

            modelBuilder.Entity("web_api.GameModel.HexTile", b =>
                {
                    b.HasOne("web_api.GameModel.Sites.SiteBase", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("web_api.GameModel.Items.ItemBase", b =>
                {
                    b.HasOne("web_api.GameModel.AvatarModel.CreatureBase", null)
                        .WithMany("Backpack")
                        .HasForeignKey("CreatureBaseId");
                });

            modelBuilder.Entity("web_api.GameModel.AvatarModel.CreatureBase", b =>
                {
                    b.Navigation("Backpack");
                });
#pragma warning restore 612, 618
        }
    }
}
